import { useState, useRef, useEffect } from "react";
import ChatSidebar from "@/components/chat/ChatSidebar";
import ChatMessage, { Message } from "@/components/chat/ChatMessage";
import ChatInput from "@/components/chat/ChatInput";
import { Sparkles } from "lucide-react";

const SUGGESTIONS = [
  "What checks should I do before raising a PR?",
  "How to verify a report?",
  "Locator for the login button?",
  "What is the expected result for <scenario>?",
];

const MOCK_RESPONSES: Record<string, { content: string; sources?: string[] }> = {
  "locator for the login button?": {
    content: `• Locator Name: \${loginBtn}
• Code Snippet: = xpath://*[@type='submit' or @name='login']
• Description: Button to submit the login credentials.`,
    sources: ["SAF_Common_Keywords_Locators_v1.0.xlsx"],
  },
  "how to verify a report?": {
    content: `• Verifying Actual Steps: Ensure the report matches the script exactly, including words, spaces, punctuation, periods, and case sensitivity, especially for data not generated by the backend.
• Verifying Actual Steps: Ensure there is no cosmetic mistake in the report.
• Verifying report properties: Test Description must be identical in both the script and the report.`,
    sources: ["Report_Verification_SOP.pdf"],
  },
  "what checks should i do before raising a pr?": {
    content: `Before raising a PR, ensure:
• All tests pass locally
• Code follows style guidelines
• No console.log statements left
• Documentation is updated
• Branch is up to date with main`,
    sources: ["PR_Checklist.md"],
  },
};

const Chat = () => {
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (content: string) => {
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content,
    };
    setMessages((prev) => [...prev, userMessage]);
    setIsLoading(true);

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    const lowerContent = content.toLowerCase();
    const mockResponse = Object.entries(MOCK_RESPONSES).find(([key]) =>
      lowerContent.includes(key)
    );

    const assistantMessage: Message = {
      id: (Date.now() + 1).toString(),
      role: "assistant",
      content: mockResponse
        ? mockResponse[1].content
        : "I couldn't find a specific answer for that question. Please try rephrasing or check the documentation.",
      sources: mockResponse ? mockResponse[1].sources : undefined,
      isError: !mockResponse,
    };

    setMessages((prev) => [...prev, assistantMessage]);
    setIsLoading(false);
  };

  const handleClearChat = () => {
    setMessages([]);
  };

  const handleSuggestionClick = (suggestion: string) => {
    handleSend(suggestion);
  };

  return (
    <div className="h-screen w-full flex bg-background overflow-hidden">
      {/* Sidebar */}
      <ChatSidebar
        isCollapsed={sidebarCollapsed}
        onToggle={() => setSidebarCollapsed(!sidebarCollapsed)}
        onClearChat={handleClearChat}
        suggestions={SUGGESTIONS}
        onSuggestionClick={handleSuggestionClick}
      />

      {/* Main Chat Area */}
      <main className="flex-1 flex flex-col min-w-0">
        {/* Header */}
        <header className="flex items-center justify-between px-6 py-4 border-b border-border bg-card/50 backdrop-blur-sm">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-primary flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div>
              <h1 className="font-bold text-lg text-foreground">Spotline Knowledge Assistant</h1>
              <p className="text-xs text-muted-foreground">
                Ask questions from Spotline SOPs, PR review checklist, validation checklist, and UI locators.
              </p>
            </div>
          </div>
        </header>

        {/* Messages Area */}
        <div className="flex-1 overflow-y-auto p-6">
          {messages.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center animate-fade-in">
              <div className="w-20 h-20 rounded-2xl bg-gradient-hero flex items-center justify-center mb-6 shadow-lg animate-float">
                <Sparkles className="w-10 h-10 text-white" />
              </div>
              <h2 className="text-2xl font-bold text-foreground mb-2">
                How can I help you today?
              </h2>
              <p className="text-muted-foreground max-w-md mb-6">
                <strong>Tip:</strong> Ask specific questions like "before raising PR" or "locator for login button".
              </p>
              <div className="flex flex-wrap gap-2 justify-center max-w-lg">
                {SUGGESTIONS.slice(0, 3).map((suggestion, index) => (
                  <button
                    key={index}
                    onClick={() => handleSuggestionClick(suggestion)}
                    className="px-4 py-2 rounded-full bg-secondary hover:bg-secondary/80 text-sm text-foreground transition-colors border border-border"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="max-w-4xl mx-auto space-y-6">
              {messages.map((message) => (
                <ChatMessage key={message.id} message={message} />
              ))}
              {isLoading && (
                <div className="flex gap-4 animate-fade-in">
                  <div className="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-white animate-pulse" />
                  </div>
                  <div className="flex items-center gap-2 p-4 bg-card border border-border rounded-2xl rounded-tl-md">
                    <div className="flex gap-1">
                      <span className="w-2 h-2 rounded-full bg-primary animate-bounce" style={{ animationDelay: "0ms" }} />
                      <span className="w-2 h-2 rounded-full bg-primary animate-bounce" style={{ animationDelay: "150ms" }} />
                      <span className="w-2 h-2 rounded-full bg-primary animate-bounce" style={{ animationDelay: "300ms" }} />
                    </div>
                    <span className="text-sm text-muted-foreground">Thinking...</span>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          )}
        </div>

        {/* Input */}
        <ChatInput onSend={handleSend} isLoading={isLoading} />
      </main>
    </div>
  );
};

export default Chat;
